### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by GabrielAtlasPower** [matth-x/ArduinoOcppSimulator#3]
Hi. I'm trying to use this simulator in Windows 11 using Ubuntu. Here is the problem that I facing:

![Captura de tela 2023-04-19 133746](https://user-images.githubusercontent.com/130501816/233142670-7fc923c7-b5ee-4103-83fd-bec4d4e5420e.png)

**Comment by GabrielAtlasPower** [comment]
Yes, I'm in this directory. I tried rerun cmake  :

`root@LAPTOP-ATLAS-3:/home/gabrielmanoel/ArduinoOcppSimulator# cmake . ./build
-- Configuring done
CMake Warning (dev) at CMakeLists.txt:20 (add_executable):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /home/gabrielmanoel/ArduinoOcppSimulator/src/main.cpp
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/gabrielmanoel/ArduinoOcppSimulator
root@LAPTOP-ATLAS-3:/home/gabrielmanoel/ArduinoOcppSimulator# cmake --build ./build
Error: could not load cache
root@LAPTOP-ATLAS-3:/home/gabrielmanoel/ArduinoOcppSimulator# cmake --install ./build
CMake Error: Error processing file: /home/gabrielmanoel/ArduinoOcppSimulator/build/cmake_install.cmake
root@LAPTOP-ATLAS-3:/home/gabrielmanoel/ArduinoOcppSimulator# ls
CMakeCache.txt  CMakeLists.txt  Makefile   ao_store  build-webapp         lib     src
CMakeFiles      LICENSE         README.md  build     cmake_install.cmake  public  webapp-src
root@LAPTOP-ATLAS-3:/home/gabrielmanoel/ArduinoOcppSimulator#`

**Comment by GabrielAtlasPower** [comment]
worked with 'cmake --build .' 
I'm enjoying this simulator. Thank you!

**Comment by matth-x** [comment]
Cool! And thanks for sharing the logs, there was another issue in the CMakeLists.txt.

I don't know why the build files don't go into the ./build folder on your machine, but I will keep an eye on it if I see a similar behavior on another machine.

**Comment by GabrielAtlasPower** [comment]
Great! Thank you for the fast replies.

**Comment by matth-x** [comment]
@GabrielAtlasPower Thanks again for remarking the cmake issue. I double-checked the instructions and found my mistake. Now the instructions should work again.
